# 模型与设备
model:
  model_path: /mnt/data/model/Qwen2.5-VL-7B-Instruct
  device: cuda          # 或 cpu
  dtype: auto           # torch dtype 字符串或 auto

# 数据集位置
data:
  metadata_path: ../eval_dataset/test_metadata.json
  base_dir: ../eval_dataset

# 生成参数
gen:
  temperature: 0.8
  max_new_tokens: 2048

# 运行控制
run:
  max_attempts: 5       # 递归修复最多尝试次数
  limit: 5              # 仅处理前 N 条；为 null/删除该项则处理全部

# 输出目录
outputs:
  json_dir: output/original-output-inputwithimg  # 保存全部输出结果为json格式，方便后续评测、查看结果使用
  tex_dir: output/output-tex-inputwithimg  # 使用正则匹配```Tex .... ``` 得到tex文件
  pdf_dir: save/pdf  # 尝试编译tex文件，如果成功，则保存为pdf 以及 png 文件
  png_dir: save/png
  log_dir: save/log  # 尝试编译tex文件，如果不成功或有warning，则保存错误日志到 log 文件夹中
