# 顶层定义变量
checkpoint: 40  # 检查点
model_name: Qwen2.5-VL-32B-Instruct  # 基础模型名
lora_task_id: lora_exp2_checkpoint  # 修改lora保存路径
instruction_model_name: gpt-5-2025-08-07
# 模型与设备
model:
  model_path: /mnt/data/model/Qwen2.5-VL-32B-Instruct  # 基础模型路径
  device: auto  # cuda
  dtype: auto
  enable_lora: False # True  # 是否要开启Lora权重
  # lora_path:  /home/yuwenhan/LLaMA-Factory/saves/Qwen2.5-VL-7B-Instruct/lora/train_2025-09-04-13-44-28/checkpoint-${checkpoint} # /path/to/checkpoint-${checkpoint} # Lora 权重的绝对路径
  lora_path: /home/yuwenhan/LLaMA-Factory/saves/Qwen2.5-VL-7B-Instruct/lora/train_2025-09-06-16-37-47/checkpoint-${checkpoint}
  lora_merge: False # True  # 是否要合并模型与权重

pipeline:
  two_stage: true            # 开启两阶段：优先读取 instruction/*.md 作为提示
  require_instruction: false # 若为 true、且找不到对应 .md，则跳过该样本；false 时会回退到 caption

# 数据集位置
data:
  metadata_path: ../eval_dataset/test_metadata.json
  base_dir: ../eval_dataset
  instruction_dir: ../two_strategies/instruction                 # NEW: 指令Markdown根目录
  instruction_model_tag: gpt-5-2025-08-07   # NEW: 子目录，可留空；为空时在 instruction/** 递归查找

# 生成参数配置
gen:
  do_sample: true
  temperature: 0.8
  max_new_tokens: 2048
  top_p: 0.9

# 运行控制
run:
  max_attempts: 5  # 重采样最大采样次数
  limit: 15   # null  # 表示要处理文件条目总数，如果不填，则表示处理文件中所有条目


# 启用 LoRA 时的输出目录
outputs_lora:
  json_dir: output/lora/${lora_task_id}${checkpoint}/original-output
  tex_dir:  output/lora/${lora_task_id}${checkpoint}/output-tex
  pdf_dir:  output/lora/${lora_task_id}${checkpoint}/pdf
  png_dir:  output/lora/${lora_task_id}${checkpoint}/png
  log_dir:  output/lora/${lora_task_id}${checkpoint}/log

# 不启用 LoRA 时的输出目录
outputs_base:
  json_dir: output/base/${model_name}/original-output
  tex_dir:  output/base/${model_name}/output-tex
  pdf_dir:  output/base/${model_name}/pdf
  png_dir:  output/base/${model_name}/png
  log_dir:  output/base/${model_name}/log

outputs_instruct:
  json_dir: output/instruct/${instruction_model_name}/original-output
  tex_dir:  output/instruct/${instruction_model_name}/output-tex
  pdf_dir:  output/instruct/${instruction_model_name}/pdf
  png_dir:  output/instruct/${instruction_model_name}/png
  log_dir:  output/instruct/${instruction_model_name}/log


# 输出log保存路径
output_log:
  log_dir : log/